postgresql: &postgresql
  adapter: postgresql
  encoding: utf8

development: &development
  <<: *postgresql
  host:     <%= ENV['DATA_ROOMS_DB_HOST']     %>
  database: <%= ENV['DATA_ROOMS_DB_DATABASE'] %>
  username: <%= ENV['DATA_ROOMS_DB_USER']     %>
  password: <%= ENV['DATA_ROOMS_DB_PASSWORD'] %>
  min_messages: warning
  pool: 2
  timeout: 5000

staging:
  <<: *development

test:
  <<: *postgresql
  host:     <%= ENV['DATA_ROOMS_DB_HOST']     %>
  database: <%= ENV['DATA_ROOMS_DB_DATABASE'] %>
  username: <%= ENV['DATA_ROOMS_DB_USER']     %>
  password: <%= ENV['DATA_ROOMS_DB_PASSWORD'] %>

production:
  <<: *postgresql
  host:     <%= ENV['DATA_ROOMS_DB_HOST']     %>
  database: <%= ENV['DATA_ROOMS_DB_DATABASE'] %>
  username: <%= ENV['DATA_ROOMS_DB_USER']     %>
  password: <%= ENV['DATA_ROOMS_DB_PASSWORD'] %>
